/**
 * SpidaverseMark — the F1 KEYSTONE mark. Generated by gen-f1-prod.mjs.
 *
 * FIXED PARAMETERS (authoritative; do NOT edit this file by hand):
 *   head:   { cy: 39, rx: 8.5, ry: 7.5 }
 *   thorax: { cy: 55, rx: 12.5, ry: 10 }
 *   abd:    { top: 64, bot: 94, rx: 13.5 }
 *   hipT:   [-41, -13, 17, 48]
 *   legs:   [[[23,-62],[19,-26]], [[25,-32],[20,4]], [[25,4],[20,36]], [[23,36],[19,66]]]
 *   w: 3.8, frame: "octagon", inner: true, clamp: true, R: 52, frameW: 1.8
 *
 * Legs TOUCH the frame. Each terminates on the octagon's CENTRELINE, so its
 * round cap is buried inside the frame stroke: the junction reads as solid,
 * with no antialiasing seam (a flush-to-inner-edge tangency shows one) and no
 * ink past the frame's outer edge. Verified on the emitted geometry:
 * frame junction rho = 1.000 — which is the centreline exactly, and is
 * checked two-sided, so a leg that STOPS SHORT fails as loudly as one that
 * overshoots. Head clearance = 1.121 (must be > 1).
 *
 * These numbers are a proof, not a comment. Do not edit the parameters
 * or the path data without re-running gen-f1-prod.mjs, which recomputes
 * both figures and THROWS rather than emit a mark whose ink escapes the
 * frame or collides with the head.
 *
 * Colour: currentColor only. Set the colour on an ancestor or via
 * className. Scales cleanly from a 16px nav slot to a 128px hero.
 */
import * as React from "react";

export interface SpidaverseMarkProps {
  className?: string;
  /** Accessible name. Omit for a purely decorative mark (aria-hidden). */
  title?: string;
}

export function SpidaverseMark({ className, title }: SpidaverseMarkProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 120 120"
      width="1em"
      height="1em"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...(title ? { role: "img" } : { "aria-hidden": true })}
    >
      {title ? <title>{title}</title> : null}
      <polygon points="108.04,79.9 79.9,108.04 40.1,108.04 11.96,79.9 11.96,40.1 40.1,11.96 79.9,11.96 108.04,40.1" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round"/>
      <polygon points="94.59,74.33 74.33,94.59 45.67,94.59 25.41,74.33 25.41,45.67 45.67,25.41 74.33,25.41 94.59,45.67" fill="none" stroke="currentColor" strokeWidth="1.1" strokeLinejoin="round" opacity="0.55"/>
      <polyline points="69.43,48.44 80.23,28.13 89.07,23.82" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="50.57,48.44 39.77,28.13 30.93,23.82" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="72.18,52.75 93.38,39.5 105.61,40.36" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="47.82,52.75 26.62,39.5 14.39,40.36" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="71.95,57.92 96.89,59.66 106.14,66.38" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="48.05,57.92 23.11,59.66 13.86,66.38" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="68.36,62.43 86.97,75.95 93.85,91.4" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="51.64,62.43 33.03,75.95 26.15,91.4" fill="none" stroke="currentColor" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 60 64 C 69.18 64 73.5 73 73.5 82.6 C 73.5 89.2 67.29 94 60 94 C 52.71 94 46.5 89.2 46.5 82.6 C 46.5 73 50.82 64 60 64 Z" fill="currentColor"/>
      <ellipse cx="60" cy="55" rx="12.5" ry="10" fill="currentColor"/>
      <ellipse cx="60" cy="39" rx="8.5" ry="7.5" fill="currentColor"/>
    </svg>
  );
}

export default SpidaverseMark;
